spring:
  application:
    name: ms-user
  datasource:
    url: jdbc:postgresql://localhost:5433/user_db
    username: postgres
    password: postgres
  jpa:
      database: POSTGRESQL
      show-sql: true
      hibernate:
        ddl-auto: none
  liquibase:
      change-log: classpath:liquibase/changelog-master.yml
